output_dir: runs/naive_resampler_test_v2

basis_states:
  basis_state_dir: /thfs3/home/sysu__netlab/xlc_DL_lab/packages/deepdrivewe/deepdrivewe/examples/amber_nacl_hk/inputs
  basis_state_ext: .ncrst
  initial_ensemble_members: 5

basis_state_initializer:
  top_file: /thfs3/home/sysu__netlab/xlc_DL_lab/packages/deepdrivewe/deepdrivewe/examples/amber_nacl_hk/common_files/nacl.parm7
  reference_file: /thfs3/home/sysu__netlab/xlc_DL_lab/packages/deepdrivewe/deepdrivewe/examples/amber_nacl_hk/inputs/bstates/bstate.ncrst

num_iterations: 50

simulation_config:
  amber_config:
    amber_exe: sander
    input_file: /thfs3/home/sysu__netlab/xlc_DL_lab/packages/deepdrivewe/deepdrivewe/examples/amber_nacl_hk/common_files/md.in
    top_file: /thfs3/home/sysu__netlab/xlc_DL_lab/packages/deepdrivewe/deepdrivewe/examples/amber_nacl_hk/common_files/nacl.parm7
  reference_file: /thfs3/home/sysu__netlab/xlc_DL_lab/packages/deepdrivewe/deepdrivewe/examples/amber_nacl_hk/inputs/bstates/bstate.ncrst

inference_config:
  # The number of simulations to maintain per bin
  sims_per_bin: 5
  # Maximum weight allowed for a single simulation
  max_allowed_weight: 0.25
  # Minimum weight allowed for a single simulation
  min_allowed_weight: 10e-40

# The target threshold for the progress coordinate
# to be considered in the target state.
target_states:
    - label: bound_state
      pcoord: [2.6]

compute_config:
  name: th
