# Configuration file for the NTL9 folding example using OpenMM

# The output directory for the runs
output_dir: runs/ntl9-v1

# The number of iterations to run the ensemble for
num_iterations: 1

# The basis states to use for the ensemble
basis_states:
  # The directory containing the basis states sub directories
  basis_state_dir: /thfs3/home/sysu__netlab/xlc_DL_lab/packages/deepdrivewe/examples/openmm_ntl9_ddwe_vista/inputs
  # The file extension for the basis state files
  basis_state_ext: .pdb
  # The number of basis states to use
  initial_ensemble_members: 1
  # Whether to randomly initialize the ensemble members if there
  # are more basis state files than initial ensemble members
  randomly_initialize: true

# Strategy for initializing the basis state progress coordinates
basis_state_initializer:
  # The path to the reference PDB file
  reference_file: /thfs3/home/sysu__netlab/xlc_DL_lab/packages/deepdrivewe/examples/openmm_ntl9_ddwe_vista/common_files/reference.pdb

# The configuration for the simulation
simulation_config:
  # The OpenMM configuration
  openmm_config:
    # The number of nanoseconds to run each simulation for (10 ps)
    simulation_length_ns: 0.01
    # How often to report frames in picoseconds
    report_interval_ps: 2.0
    # The time step to use in picoseconds
    dt_ps: 0.002
    # The temperature to run the simulation at
    temperature: 300.0
    # The solvent type
    solvent_type: implicit
    # The hardware platform to run the simulation on
    hardware_platform: CPU

  # The path to the reference PDB file
  reference_file: /thfs3/home/sysu__netlab/xlc_DL_lab/packages/deepdrivewe/examples/openmm_ntl9_ddwe_vista/common_files/reference.pdb

# The configuration for training
train_config:
  # The path to the CVAE model configuration file
  config_path: /thfs3/home/sysu__netlab/xlc_DL_lab/packages/deepdrivewe/examples/openmm_ntl9_ddwe_vista/cvae-config.yaml
  # The path to the CVAE model weights file
  checkpoint_path: /thfs3/home/sysu__netlab/xlc_DL_lab/packages/deepdrivewe/examples/openmm_ntl9_ddwe_vista/checkpoint-epoch-100.pt

# The configuration for the inference
inference_config:
  # The path to the CVAE model configuration file
  ai_model_config_path: /thfs3/home/sysu__netlab/xlc_DL_lab/packages/deepdrivewe/examples/openmm_ntl9_ddwe_vista/cvae-config.yaml
  # The path to the CVAE model weights file
  ai_model_checkpoint_path: /thfs3/home/sysu__netlab/xlc_DL_lab/packages/deepdrivewe/examples/openmm_ntl9_ddwe_vista/checkpoint-epoch-100.pt

  # The number of neighbors to use for LOF
  lof_n_neighbors: 2
  # The distance metric to use for LOF [cosine, minkowski]
  lof_distance_metric: cosine

  # The number of simulations to maintain per bin (we only have one bin)
  # so this is the total number of simulations to maintain
  sims_per_bin: 2
  # The number of simulations to resample in each iteration
  consider_for_resampling: 2
  # The maximum number of resamples to perform in each iteration
  max_resamples: 2

# The target threshold for the progress coordinate
# to be considered in the target state.
target_states:
    - label: folded
      pcoord: [1.0]

# The settings for the compute environment
compute_config:
  # The name of the compute platform to use
  name: th
